2024-04-19 17:11:49,304:ERROR:Ошибка при добавлении транзакции: list index out of range
2024-04-19 17:56:55,425:ERROR:Ошибка при добавлении транзакции: list index out of range
2024-04-19 18:23:52,802:ERROR:Ошибка при добавлении транзакции: NOT NULL constraint failed: transactions.amount
2024-04-26 18:51:30,394:ERROR:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-04-26 18:51:30,396:ERROR:Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Глеб\Documents\GitHub\finance_manager\srs\bot.py", line 105, in category_step
    bot.send_message(
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

2024-04-26 18:52:12,153:ERROR:Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found
2024-04-26 18:52:12,155:ERROR:Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\__init__.py", line 1206, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\util.py", line 150, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "C:\Users\Глеб\Documents\GitHub\finance_manager\srs\bot.py", line 105, in category_step
    bot.send_message(
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\__init__.py", line 1742, in send_message
    apihelper.send_message(
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\apihelper.py", line 270, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\apihelper.py", line 167, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Глеб\AppData\Roaming\Python\Python312\site-packages\telebot\apihelper.py", line 194, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: chat not found

